### PR TITLE
Add inline and hot module replacement

### PR DESCRIPTION
**Pull request by chiplay**
Address https://github.com/webpack/grunt-webpack/issues/36

### CODE REVIEW

**Comment by unindented** [comment]
@sokra What would be missing for this to get merged?

**Comment by chiplay** [comment]
@sokra the PR is here as well :)

**Comment by jcreamer898** [comment]
Works great!

**Comment by jcreamer898** [comment]
Well done @chiplay

**Comment by chiplay** [comment]
@jcreamer898 thanks - merged :tada:

**Comment by danny-andrews** [comment]
This doesn't appear to work anymore.

**Pull request merged**
