### PR TITLE
fix: build fails with an `resolve.alias` called `plugins` fix #48

### LINKED ISSUE #48: build fails with an `resolve.alias` called `plugins`
I am working on using webpack for our current project and came up with a strange bug in grunt-webpack.
We have a modular structure and some modules are called `plugins`. They are found in a subdirectory we resolved before with a requirejs configuration. Now with webpack I created an alias in `resolve.alias` like `plugins: 'source/plugins'`. With webpack used globally everything works fine, but when used with `grunt-webpack` I get a strange `undefined is not a function` error from grunt.
`grunt webpack --stack` prints out this (shortened):
```
Warning: undefined is not a function Use --force to continue.
TypeError: undefined is not a function
  at fixPlugins (C:\Users\foellerich\Git\epages-ui\node_modules\grunt-webpack\lib\getWithPlugins.js:25:31)
  at C:\Users\foellerich\Git\epages-ui\node_modules\grunt-webpack\lib\getWithPlugins.js:43:6
  at Array.forEach (native)
  at fixPlugins (C:\Users\foellerich\Git\epages-ui\node_modules\grunt-webpack\lib\getWithPlugins.js:41:21)
  at C:\Users\foellerich\Git\epages-ui\node_modules\grunt-webpack\lib\getWithPlugins.js:43:6
  at Array.forEach (native)
[...]
```
When renaming the alias at least this strange behavior is fixed. It seems as if the `fixPlugins`-method is crawling the whole config for the key `plugins` and then tries to resolve it as a plugin, even if it is just an alias.

### PR DESCRIPTION
**Pull request by maksimr**

### CODE REVIEW

**Comment by sokra** [comment]
Please check the spacing.

**Comment by maksimr** [comment]
@sokra we use 4 space?

Thanks

**Comment by sokra** [comment]
Please use tabs.

**Comment by maksimr** [comment]
@sokra done

**Comment by sokra** [comment]
Thanks

**Comment by maksimr** [comment]
No problems!

It will be nice to have it in npm

**Pull request merged**
